[package]
name = "odoorpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
reqwest = "0.11.18"
serde = "1.0.163"
serde_xmlrpc = "0.2.0"
thiserror = "1.0.40"
xmlrpc = "0.15.1"
