[package]
name = "odoorpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
reqwest = "0.11.18"
serde = "1.0.163"
serde_xmlrpc = { version= "0.2.0", git = "https://github.com/cloud303-cholden/serde-xmlrpc.git" }
thiserror = "1.0.40"
xmlrpc = "0.15.1"
