[package]
name = "odoorpc"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.18", default-features = false, features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
